# Generated by Django 4.0.5 on 2022-07-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='store',
        ),
    ]
